[build]
  command = "npm run build"
  publish = "dist"

# Handle static assets
[[redirects]]
  from = "/_astro/*"
  to = "/_astro/:splat"
  status = 200

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "./netlify/functions/entry"
  status = 200
  force = true 